### ISSUE TITLE
A non-stack connection to RPi

### ISSUE THREAD

**Issue by smetanadvorak** [geeekpi/upsplus#116]
Hi, 

I was wondering if there is a neat way to connect the EP-0136 to RPi, but using wires instead of stacking one on top of another?
In my design, the two boards actually end up facing each other, so I can't use the EP-0136's supply pins that target the 1-3-5-4-6-10 pins of the RPi. I didn't manage to find where I could solder or insert my own connector. Would it be possible to give me a hint?

Thanks!

**Comment by yoyojacky** [comment]
Hi smetanadvorak, 
It seems like it will be a little hard to do due to the UPS plus powered the Raspberry Pi via the pogopin which against the soldering point to the Raspberry Pi GPIO, and it will contact with Raspberry Pi 's I2C via GPIO, you may need to wire the 3.3v and SDA、SCL pin to UPS, and wire the 5V and GND to UPS too. according to the Raspberry Pi's Pinout, but once you have soldering the wire to UPS and mismatch the wires, it may damage your devcie and it all of your own risks.
