### ISSUE TITLE
In normal AC charging mode, Raspi is simply switched off and Raspi does not start when AC is back

### ISSUE THREAD

**Issue by Jambo52** [geeekpi/upsplus#135]
1.)In normal AC charging mode, Raspi is simply switched off after a restart countdown time without shutdown.
2.)The UPS board switches off the Raspi without shutdown at 3700mv and also the UPS-board.

Current power state: normal
Shutdown countdown: 130 sec
Automatically turn on when there is external power supply!
Restart countdown: 130 sec

When AC is back, however, the board starts charging but the Raspi does not start, but only after a while even with full batteries.

i2cset -y 1 0x17 25 1 is set.

Why is that?

**Comment by KrzePikPL** [comment]
I have the same problem with version v10, after startup it works for about 1 minute, then to turn on the device I have to manually remove the battery but with no improvement, after restoring the power the same problem persists

**Comment by Jambo52** [comment]
I didn't solve it either. I switched because the support doesn't work here either. I have now connected the board EP-0136. This does shutdown and starts even after a power failure. Unfortunately I can't help you either.

**Comment by KrzePikPL** [comment]
I don't know what board would work, so that it could check the charging status and start automatically, it's a simple script, and the second board I have has problems with it. And the spontaneous turning off of the board disqualifies it because then it turns on itself, but at an unspecified time it is possible that it is a problem with the switching on times because the board has an RTC, so maybe you need to look for it there

**Comment by KrzePikPL** [comment]
I wonder if if I used the X728 software (https://wiki.geekworm.com/X728#X728_V2.5), whether the device would accept it and start working with these functions. Because there is clearly a problem with the clock on the original board

**Comment by yoyojacky** [comment]
No, it is not fit for X728 software, it just fit for this repo： https://github.com/geeekpi/upsplus.git
